version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install -g @angular/cli@11.2.7
      - npm install
  build:
    commands:
      - echo "Building Angular project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/ s3://chordbomb.com --delete
